DEFAULT_MINIMUM_BARS = 200
DEFAULT_RECOMMENDED_BARS = 260
VALID_CANDLE_STATUSES = frozenset({"closed", "unclosed"})
MAJOR_CANDLE_PATTERNS = (
    "cdl_doji",
    "cdl_hammer",
    "cdl_inverted_hammer",
    "cdl_hanging_man",
    "cdl_shooting_star",
    "cdl_engulfing",
    "cdl_harami",
    "cdl_piercing",
    "cdl_dark_cloud_cover",
    "cdl_morning_star",
    "cdl_evening_star",
    "cdl_3white_soldiers",
    "cdl_3black_crows",
)
FULL_CANDLE_PATTERNS = MAJOR_CANDLE_PATTERNS + (
    "cdl_marubozu",
    "cdl_spinning_top",
    "cdl_long_legged_doji",
    "cdl_belt_hold",
    "cdl_kicking",
    "cdl_takuri",
    "cdl_rickshaw_man",
)

CORE_INDICATORS = (
    "sma_20",
    "sma_50",
    "sma_200",
    "ema_20",
    "ema_50",
    "macd",
    "adx_14",
    "plus_di_14",
    "minus_di_14",
    "sar",
    "rsi_14",
    "stoch",
    "willr_14",
    "cci_20",
    "roc_10",
    "atr_14",
    "natr_14",
    "bbands_20_2",
    "obv",
    "mfi_14",
    "ad",
    "adosc",
)

EXTENDED_INDICATORS = (
    "aroon_25",
    "aroonosc_25",
    "ppo_12_26_9",
    "trix_30",
    "kama_10",
    "linearreg_slope_14",
    "mom_10",
    "cmo_14",
)

DEFAULT_THRESHOLDS = {
    "adx_trend_present": 20.0,
    "adx_strong_trend": 25.0,
    "mfi_overbought": 80.0,
    "mfi_oversold": 20.0,
    "rsi_overbought": 70.0,
    "rsi_oversold": 30.0,
    "stochastic_upper_zone": 80.0,
    "stochastic_lower_zone": 20.0,
    "volatility_high_percentile": 0.75,
    "volatility_low_percentile": 0.25,
}

DEFAULT_WINDOWS = {
    "adx": 14,
    "aroon": 25,
    "atr": 14,
    "bbands": 20,
    "cci": 20,
    "cmo": 14,
    "ema_fast": 12,
    "ema_signal": 9,
    "ema_slow": 26,
    "kama": 10,
    "kama_fast": 2,
    "kama_slow": 30,
    "linearreg_slope": 14,
    "mfi": 14,
    "mom": 10,
    "obv_direction": 5,
    "ppo_fast": 12,
    "ppo_signal": 9,
    "ppo_slow": 26,
    "roc": 10,
    "rsi": 14,
    "sma_fast": 20,
    "sma_medium": 50,
    "sma_slow": 200,
    "stochastic": 5,
    "stochastic_slowd": 3,
    "stochastic_slowk": 3,
    "trix": 30,
    "volatility_regime": 50,
    "willr": 14,
}
